const div1 = dom.create('<div id="parent"><span id="span"></span></div>');
const div2 = dom.create('<div id="child1">111</div>');
const div3 = dom.create("<div id='child2'>222</div>");
//dom.append(body, div1);
dom.append(body, div2);
dom.append(body, div3);
dom.wrap(div2, div1);
dom.wrap(div3, div1);
//console.log(dom.find(".red")[1]);
//console.log(dom.find("#parent>#span")[0]);
//console.log(dom.index(test2));
// let t = dom.find("#parent")[0];
// dom.each(dom.children(t), n => dom.style(n, "color", "red"));
//console.log(dom.each(dom.children(t)));
//console.log(t);
//dom.each();
//console.log(dom.find("#parent")[0]);
//console.log(dom.previous(child2));
// let x = dom.find(".red", test2)[0];
// console.log(x);
// fn = () => {
//   console.log("点击了");
// };
// dom.on(test, "click", fn);
// dom.off(test, "click", fn);
// dom.class.add(test, "red");
// dom.class.add(test, "blue");
// dom.class.remove(test, "red");
// console.log(dom.class.has(test, "red"));
// dom.style(test, "border", "1px solid red");
// dom.style(test, "border");
// console.log(dom.style(test, "border"));
// dom.style(test, { border: "1px solid black" });
// let x = dom.html(parent);
// console.log(x);
// let y = dom.html(child1);
// console.log(y);
// dom.text(child1, "hahaha");
// let x = dom.text(child1);
// console.log(x);
//dom.before(test, div1);
//let x = dom.remove(div1);
//dom.append(body, x);
//let y = dom.empty(div1);
//console.log(y);
//dom.wrap(div1, div2);
//dom.attr(child, "title", "Hi,I am lirongyue");
//dom.attr(parent, "title", "Hi,I am frank");
//let x = dom.attr(child2, "title");
//console.log(`title:${x}`);
